In [13]:
import numpy as np
file_path = '/Users/aqsa/Desktop/nyc_taxis.csv'

taxi = np.genfromtxt(file_path, delimiter=',', skip_header= True)
print(taxi)

[[2.016e+03 1.000e+00 1.000e+00 ... 1.165e+01 6.999e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 8.000e+00 5.430e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 0.000e+00 3.780e+01 2.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 5.000e+00 6.334e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 8.950e+00 4.475e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 5.484e+01 2.000e+00]]


In [16]:
speed = taxi[:, 7] / (taxi[:, 8] / 3600)
mean_speed = speed.mean()
print("Mean value:", mean_speed)

Mean value: 32.24258580925573


In [30]:
rides_feb = taxi[taxi[:,1] == 2,1]
print("Number of rides in February:", rides_feb.shape[0])


Number of rides in February: 13333


In [26]:
print(taxi[taxi[:,-3] > 50, -3].shape[0])


16


In [28]:
print(taxi[taxi[:,6] == 2,6].shape[0])

11832
